name: CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'gh-pages'

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to the ${{ github.event.inputs.branch }} branch
        run: |
          cd $BUILD_DIR
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Build"
          echo "https://github.com/$GITHUB_REPOSITORY.git
          git remote add origin https://github.com/$GITHUB_REPOSITORY.git
          git push -f -u origin ${{ github.event.inputs.branch }}
        env:
          BUILD_DIR: dist
